# https://eslint.org/docs/rules/
# https://eslint.org/docs/user-guide/configuring#specifying-environments
# env:
#   browser: true
#   commonjs: true
#   es6: true
#   node: true
#   jquery: true
extends:
  - 'eslint:recommended'
plugins:
  - 'babel'
# settings:
#   react:
#     version: 'detect'
parser: 'babel-eslint'
parserOptions:
  # ecmaVersion: 2018
  # ecmaVersion: 7
  # ecmaVersion: 5
  sourceType: module
  # files:
  #   -
  #     patterns: '**/*.jsx'
# {{{ Rules
rules:
  no-debugger: warn
  no-console: warn
  # no-console: 0 # DEBUG?
  # no-const-assign: error
  # no-unused-vars: 0 # DEBUG?
  no-unused-vars:
    - warn
    -
      vars: local
      varsIgnorePattern: ^_
  # camelcase:
  #   - warn
  # indent:
  #   - warn
  #   - 2
  linebreak-style:
    - error
    - unix
  # quotes:
  #   - warn
  #   - single
  curly: # single line statements without curly braces
    - warn
    # - always
  # curly: 0
  semi: # end-linbe semicolons
    - warn
    - always
  # semi: 0
# Rules }}}
# {{{ Globals
globals:
  System: true # Webpack dynamic import
  # config: true
  # TODO 2019.02.27, 21:24 -- Remove global variables. Use modules.
  # NOTE 2019.03.22, 12:20 -- Other globals to remove
  # xerox: true
  # env: true
  # cons: true
  # HP_environment: true
  # ResponseHandler: true
  # logger: true
# Globals }}}
overrides:
  # {{{ JS
  -
    files: '**/*.js'
    env:
      browser: true
      commonjs: true
      es6: true
      node: true
      jquery: true
  # JS }}}
  # {{{ Jest tests
  -
    files: '**/*.test.js'
    env:
      jest: true
    plugins:
      - jest
    rules:
      semi: 0
      # 'jest/no-disabled-tests': 'warn'
      # 'jest/no-focused-tests': 'error'
      # 'jest/no-identical-title': 'error'
      # 'jest/prefer-to-have-length': 'warn'
      # 'jest/valid-expect': 'error'
  # Jest tests }}}
  # {{{ BEMHTML Templates
  -
    files:
      - "*.bemhtml"
    plugins: # (ES5 mode)
      - es5 # ES5 mode! https://www.npmjs.com/package/eslint-plugin-es5
    # extends:
    #   - eslint:recommended
    #   - plugin:es5/no-es2015
    env:
      browser: true
      # commonjs: true
      # es6: false
    # {{{ Rules (ES5 mode)
    rules:
      es5/no-arrow-functions: error
      es5/no-binary-and-octal-literals: error
      es5/no-block-scoping: error
      es5/no-classes: error
      es5/no-computed-properties: error
      es5/no-default-parameters: error
      es5/no-destructuring: error
      es5/no-exponentiation-operator: error
      es5/no-for-of: error
      es5/no-generators: error
      es5/no-modules: error
      es5/no-object-super: error
      es5/no-rest-parameters: error
      es5/no-shorthand-properties: error
      es5/no-spread: error
      es5/no-template-literals: error
      es5/no-typeof-symbol: error
      es5/no-unicode-code-point-escape: error
      es5/no-unicode-regex: error

      # no-const-assign: 0
      # arrow-body-style: 0
      # arrow-parens: 0
      # arrow-spacing: 0
      # constructor-super: 0
      # generator-star-spacing: 0
      # no-class-assign: 0
      # no-confusing-arrow: 0
      # # no-const-assign: 0
      # no-dupe-class-members: 0
      # no-duplicate-imports: 0
      # no-new-symbol: 0
      # no-restricted-imports: 0
      # no-this-before-super: 0
      # no-useless-computed-key: 0
      # no-useless-constructor: 0
      # no-useless-rename: 0
      # no-var: 0
      # object-shorthand: 0
      # prefer-arrow-callback: 0
      # prefer-const: 0
      # prefer-destructuring: 0
      # prefer-numeric-literals: 0
      # prefer-rest-params: 0
      # prefer-spread: 0
      # prefer-template: 0
      # require-yield: 0
      # rest-spread-spacing: 0
      # sort-imports: 0
      # symbol-description: 0
      # template-curly-spacing: 0
      # yield-star-spacing: 0
    # Rules }}}
    # {{{ Globals
    globals:
      # See module requires option parameter for `webpack-nano-bemhtml-loader` in `webpack.config.js`
      config: true
      # All default BEMHTML mods:
      addAttrs: true
      addElemMods: true
      addJs: true
      addMix: true
      addMods: true
      appendContent: true
      apply: true
      applyCtx: true
      applyNext: true
      attrs: true
      bem: true
      block: true
      cls: true
      content: true
      def: true
      elem: true
      elemMod: true
      elemMods: true
      extend: true
      js: true
      local: true
      match: true
      mix: true
      mod: true
      mode: true
      mods: true
      oninit: true
      prependContent: true
      replace: true
      tag: true
      wrap: true
      xjstOptions : true
    # Globals }}}
  # BEMHTML Templates }}}
